### ISSUE TITLE
Pacote Java 

### ISSUE THREAD

**Issue by prof-ewerton** [ilmoruuu/ProjetoBeulch#1]
Os nomes de pacotes devem ser escritos em letras minúsculas e seguir o padrão reverse domain name, ou seja, o nome do domínio invertido. Por exemplo, “com.meudominio.meupacote”. Também não deve conter caracteres especiais.

Utilizar br.beulch.nomedaaplicacao ao invés de br.Beulch.

Para saber mais: https://napoleon.com.br/glossario/o-que-e-java-naming-conventions/

**Comment by ilmoruuu** [comment]
Olá professor Ewerton!

Estávamos dando nossos ajustes finais na aplicação e em sua organização, agradecemos sua contribuição! Resolvemos nessa última versão da _main_.

_Atenciosamente,
Murilo Lucena_

**Comment by ilmoruuu** [comment]
Olá professor Ewerton!

Estávamos dando nossos ajustes finais na aplicação e em sua organização, agradecemos sua contribuição! Resolvemos nessa última versão da main.

_Atenciosamente,
Murilo Lucena_
